name: certbot-dns-porkbun
summary: Porkbun DNS Authenticator plugin for Certbot
description: Porkbun DNS Authenticator plugin for Certbot
confinement: strict
grade: stable
base: core24
adopt-info: certbot-dns-porkbun
platforms:
  amd64:
  arm64:
  armhf:

parts:
  certbot-dns-porkbun:
    plugin: python
    source: .
    override-pull: |
      craftctl default
      craftctl set version=$(grep '^__version__' "$SNAPCRAFT_PART_SRC/certbot_dns_porkbun/__init__.py" | cut -f2 -d= | tr -d '"[:space:]"')
    build-environment:
      - SNAP_BUILD: "True"
    python-requirements:
      - requirements.txt
    build-packages:
      - gcc
      - git
      - build-essential
      - libssl-dev
      - libffi-dev
      - python3-dev
      - cargo
      - pkg-config
  certbot-metadata:
    plugin: dump
    source: .
    stage: [ setup.py, certbot-shared ]
    override-pull: |
      craftctl default
      mkdir -p $SNAPCRAFT_PART_SRC/certbot-shared

slots:
  certbot:
    interface: content
    content: certbot-1
    read:
      - $SNAP/lib/python3.12/site-packages

plugs:
  certbot-metadata:
    interface: content
    content: metadata-1
    target: $SNAP/certbot-shared
